swagger: '2.0'
info:
  description: |
    Retrieve and update contact information. Contact id is
    required for retrieval or update.
  version: 1.1.0
  title: contact
  contact:
    email: miles.ulrich@sap.com
schemes:
  - http
  - https
produces:
  - application/json
host:
  sapconcur.my.salesforce.com
basePath: /services/apexrest

paths:
  /contact:
    get:
      summary: |
        Retrieves contact using either contact id or email address.
        Only used email address if contact id is not present.
        Either contact id or email address must be preset or error will be returned.
      operationId: getContact
      description: |
        Gets contact information
      produces:
      - application/json
      parameters:
      - in: query
        name: id
        description: pass in id of contact
        required: false
        type: string
        minimum: 15
        maximum: 18
      - in: query
        name: email
        description: pass in email for contact
        required: false
        type: string
        minimum: 6
        maximum: 80
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              contact:
                $ref: '#/definitions/Contact'
        400:
          description: bad input parameter
          schema:
            $ref: '#/definitions/Rsp_Error'
    post:
      summary: upsert a contact
      operationId: upsertContact
      description: |
        Creates or updates a contact.  Update is performed if contact id is provided.
        An error will occur if attempting to create a new contact with an email that
        already exists in the system.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: contact
        description: contact info to create / update
        schema:
          $ref: '#/definitions/Contact'
      responses:
        201:
          description: item created
          schema:
            $ref: '#/definitions/Rsp_Post'
        400:
          description: invalid input, object invalid
          schema:
            $ref: '#/definitions/Rsp_Error'
        409:
          description: an existing item already exists
          schema:
            $ref: '#/definitions/Rsp_Error'

definitions:
  Contact:
    type: object
    properties:
      salesforce_id:
        type: string
        minimum: 15
        maximum: 18
      hybris_id:
        type: string
      account_id:
        type: string
        minimum: 15
        maximum: 18
      full_name:
        type: string
        maximum: 121
      first_name:
        type: string
        maximum: 40
      last_name:
        type: string
        maximum: 80
      title:
        type: string
        maximum: 255
      email:
        type: string
        maximum: 80
      phone:
        type: string
        maximum: 40
      status:
        type: string
        maximum: 255
      address:
        $ref: '#/definitions/Address'
    required:
      - account_id
      - last_name
  Address:
    type: object
    properties:
      street1:
        type: string
        maximum: 140
      street2:
        type: string
        maximum: 140
      city:
        type: string
        maximum: 80
      state_province:
        type: string
        maximum: 80
      postal_code:
        type: string
        maximum: 20
      country:
        type: string
        maximum: 80
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Rsp_Error:
    type: object
    properties:
      error:
        $ref: '#/definitions/Error'
  Rsp_Post:
    properties:
      contact_id:
          type: string
          minimum: 15
          maximum: 18